engines:
  # waiting for https://github.com/tkqubo/codeclimate-tslint/issues/26
  # tslint:
  #   enabled: true
  #   channel: beta
  #   config: tslint.json
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**"
  - "e2e/**"
  - "bin/**"
  - "karma.conf.js"
  - "protractor.conf.js"
exclude_paths:
- node_modules
- coverage
- dist
- ssl
