dist: focal
addons:
  chrome: stable
language: node_js
node_js: 14
before_install:
  - export TZ=Europe/Zurich
  - export CHROME_BIN=google-chrome-stable
  - gem install mdl
  - npm install -g @angular/cli greenkeeper-lockfile
cache:
  directories:
    - node_modules
before_script: greenkeeper-lockfile-update
script: npm run ci
after_script: greenkeeper-lockfile-upload
env:
  global:
    - secure: Uwc/4DXZ96evLZ/RNLkO8V23d/q3TeOJ9fPJCAhzNJraWR/YcSIVM8dAMicpDhXWxCJ0jSrU7Vn8StfXEVFhw8BRcgHwaOGpjKiNFYNMk9INRi0tOZq/ul6NcTm94qSq7VO18/x+qBNLbfDYYjlFOTLkgo86fa5sO3q3tDpt4Ui39Dbigavbb/ZSccL61cMYbk8+6WqF3GBzOIOmf3UP3EifmTU/W4Jt1HqglPJ0cw06ZMLf7caIH1d2Zk+qiyvt1OqAjs7OkJ2CVmJTNv1ZljwYvvcH5jWxGi0nhUHcNjWFm+HOBWkYeZ1umRojFlExZR8wc9F1SENqLbVd1V5r6cVztHrgiacWzxgcHpPBBlHwKSbq7i8lWeVkHDZte0cboFGYfs2i3+bZjxYDr9C7bioyHBMPb6rOtw5zstL63LBOgTe558YF/i3K2nrBMMJZ3j8cvuvRXDaB4PvFrIl7XpE7ZfpOlQ542N6pS8DVyTaBjhxM47w4uChD/fLwxUKfC/IWH9HYJ4spl/O1nYHp+yHa4gZ9ZYVGlTT33+D6xUoHKcfI1VkPw/rLycEyTcYfwFK/U8Aa3zqovrFBcdlKP77Qg+lO8yPLeGEEwYNcjaQippN5NFH2IM/XAGFye2fbQPoqG2gsP4xE8OB+ccTxEfnJFRbuZqqYivwR8NRU39A=
    - secure: iK1I0Nqt2hvzWLY2mf9Lo6j0MRy8BvEgIXxg3zc6ZANGq08IIuuUT5K9aoGuIVk5zYD6rrJ3Es24nGh1sWf9nZtyDwTOnjzGv2hs2fPpSjblUWhq8fwflHwOzUZddsYyGGV4i8p7BMkekfDi8uKmfXsb84S1qzhXmStlWRZ+sfv5vzAAJr8IFZ30a0Sy2ao/Q2vZz2VKjeEH6BRzm5n7IShwAK0zTsYYduNrGu/f90934WJPH4ojQoz0sLV1OvtYEty2Xyl3IqYFi0X1ftabnzVkFrLQbEA20s7DbzaZqzNY9BCYkohiMPNy7+uiNW/5UDoCchTGFEOuR2Y3KJrNBsA1VgQlvXcHeQBnpxJE/C2Bi/X4TBZbbU/y+M1j3W87O2/NUDjd9zWb4LFz1tcanzWoE92OgSUXNu1UXTV74aJGjfYweEpfDNK0IcyreIayFeAxIJKTAzPRW5E6sCNIUqVxT4rSlDw+iToSgutu09H2ZJNdMEOWg8vtPNEzBCKV33siGgIyc+AlU2RyVBs+HvTiUBUQxPoL1KZrubXNkEgPUVGB5XZUaz+wF7KgsfAF+Xfgs7E3qzdw+/8lR8vT6m5aa3b80h+nfLbvYkxKLZUXqAqjYioTc2JdM2JnI4RB1ozEY6DiNhv97MK41Fq0nZhNUoTm41sqJczVQyvtrfE=
after_success:
  - npm install -g codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=55944955a9f4d206eb7530d523e0abf2956fe916ebcad96c6d11aa751731e3f7
    codeclimate-test-reporter < coverage/lcov.info
  - CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage
    CODECLIMATE_REPO_TOKEN=7684be16-7c66-4f2d-b366-4410018d7326 codeclimate-test-reporter <
    coverage/lcov.info
  - npm install -g codecov
  - codecov
before_deploy:
  - npm run build-prod
  - cd functions && yarn install && yarn build && cd ..
deploy:
  cleanup: false
  on:
    branch: main
  provider: firebase
  edge: true
  token:
    secure: Z5bes5ca3VFRBzJ0wc4/Ly7sIMy2HDidf+d5hKspf7yETmKrxmWRt8I3ru9apxthWCn0GPWGG9UbaFJmrkCk3ZCmtBxwQcjSvXVxrs6clqyTVvOw3nQ3mJ+5i8J4d4Tyv31qvUBXG5W9cJMVzG2zcm772TZ4ml/GHW8Pb0pOSVK/v5kg/qvmOrXYtXE114rowYN+3l26lQnZxWPhSIfG+haaQbrYLZ79lJSWfQszFbwk/0gbPhAgXskq/+OPH8uarNc+qMLZ+/jfetRKJMSKmE4uR/WdRPoW67M3D5j/A+uXev12Yb2c1HZJiyXcb3Kr3lnFrRUBZk3gfO7bQT9/nOHCVeTdVf48b/GfwUwuPyZCspUQDAgupslJRF50ByArwEFHom4EJ6r6Iq2hShOEhQqwIBH6nMLToV8ENKDiQuTxcMFHaKiu9xBPwzkcffD41jrbO6VakQ5OyDuvxhFgAxyZ6ZEZMEtmkOt5BgfXE+sPu0fNf7/v719Wqnjf0OBamraGUkXx7qomjpWoAMQB6pePyd9ja51HCx6ubad0IJSA4AeoB7oesqj6KPeCE83zX5glQlOLflwg8Ai+V5X88BiOGTHK3eZtdnRIhMQ5obG1gzskxrK48WXP9f7QVGbUz08XtV9Mn0WBcdwU/LDYkqv4vNMs/z6uumcwKypoayA=
  project: sanhei-bills
