dist: trusty
addons:
  chrome: stable
language: node_js
before_install:
- export CHROME_BIN=google-chrome-stable
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
node_js:
- node
cache:
  directories:
  - node_modules
script: npm run ci
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: firebase
  token:
    secure: NJD8mIiNeHsFisH9AmimB9+IwPV6lBlu1LtDGQfh/vCsBsnzn7D5vs/N48S/4oJarrH8VuobNn6s0oFTmdduD+3N9BfZ3vxzjaZGl3M5v7tsH8InXCT8HEtnXuinv9Tn7MQpcRJZvIxXG62h7xEqKT9uRN4+WPldzUtUC1Gq80pe3//PLttZCu+ae7PeH7AXMOEb6K6Snq4GGJ/KxBVDoOPxJgsFVqAlZ2l00Rv0JW6yF1cMk3rYcr0enQeWwPQPM7PvG3slHHCecm+PXk6ojTHc3buKMt5I5rTAyVEX/sFQXhzOcPeUm4eCJuCEkueotoTtbTbPmi3am9XXAgQvy6iQH+QO0QqeBp+SuP0SFv/X1lCR2Ki7bFmPCzKmysIGdOy6SsmCzElzNN6u2BjZ/aF5eUEbj6t7d+OllF61CidoRW4sw+Br0nRvvbMVWBpNeqlIxkOSe/dBNPos6gSacl+vcttdrCP3F8zOuJCkcYnSFoPq17YrJpNtoANyxwBDo350QJFordJuluR4F/7u8Gt36LyZqAmsP9/Frv+b4pDQ8WaqsoizWKpdcLoFv1RqfHQa2uzV845zbTJTzY9wEXSBY8nNbkmxVSviNtw7RdAcwmowcGaM2DqyHDB/hq//svUE+gtg7UwAj0hncMp3IJvZjbnw04Mt5vmciZfpp58=
  project: sanhei-bills
