dist: trusty
addons:
  chrome: stable
language: node_js
before_install:
- export CHROME_BIN=google-chrome-stable
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem install mdl
cache:
  directories:
  - node_modules
script: npm run ci
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter > coverage/lcov.info
before_deploy: npm run build --prod --progress false
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: firebase
  token:
    secure: C/ijVEECipluzfapXKOnXp1dy0y65knHmVQ5oMINK6gzTxFKGxjPKvmQVkK8o50VL+zsqDcsYq/dySI357Ls8vDekLoWJqb7ZkcDGS+4vxcj4L9zjKAv6dOeLF8Ng3bXIkCJ1sNSTrzBMKS2CxHlceWiDjM6XaybGuvWLufCXvUQh7rUCeleTdvTFLBnN3zB+fpIVhruOfgoU74nhBolv9/9PWsr0P8JZA1RyN0CqYkUGbS7TkEsnKM+ih3f+e3RhF7MtCyuAoD+UegUfNhoX6GrOxMkM0eP98mnWB9p8qoTUcd+z9G44x97oNtzG9+cqhTb4B42jGcVumMdSDVZqysBvEotJMf4G+PASycdsyF+OuIr2m7yLt/dzlUn5Lv+MOOjf34BDT98KbXKyeuM9zgKtvEI/1h1VJTccZr/Is8igTtoR05+xhQ1o/W0EsMDRzCWFiApysST07am8quv3yLr8MK8dOVl0OpGGJL7oo/bw1Q3ru/bFx1iq2O/iKIr1lEiqdXs4Ubbk7l8i0eYeDP1I6vFvAeKi1j7/A1R9UQcroUBPNppHagQBfy7VfaRt20FZO8NahucoK3ZLL/1RjXwxF4pwznMXO5/quTXEcSXauxXoK7XKptgmeZ+BkfCjH7ysn6eK/SGXBHmMd6y4NLfpy7g4O9D5spqluwzDb0=
  project: sanhei-bills
env:
  global:
    secure: e1U8Hi9TTXPmVL0r1Q+BhsTn6ymXs9qtS715gycCw1hlU2QLJHdPcfVWeRljAmpYK+lsEo/YJDjhbKW5YHhdmu9GGGMML9pUVMj6kgx6O6ekHbEG4NzcAJkMOAZE1V/mz/Jr5y2qe1Vix+24RVnA7UI1o7s9bbro/CkUMRthjItjdtJqbJHosh9nGNb5LWO6eMXnVAjwmvCo7SwNE9lc89zdZQEqVzaJtFjku8GE7hPCwt2ANSRYiPN5lFT+ewU6PDhb4i3lKWgzEepuX4TAhxrLKp9HbO/O7O8xfeyZJhTKfHmlmuqpZXEsqTRsTa/NLs34hAQp5iuiJBxp9jaPqYfBz4LJCIFNaAIBN0bAgzIVlQLJXJ97U7lrdxzFAWIe4/+m+6Xd1y9/4mKS1BZEfSlKEy/aBJhwQtABrsBnEf0m84GhGPF5BDW+AkRzatxYTmkWXA7I9So1KRzNjfUO14QPJ8BnDDFiDba/gPXx8hqlINMuZ2+ttqEbWY4VPGMDeMStGMFWJ7iLNZEiWeOdyJ9ARroJmRaMTEGeRtV2baLfwADOR7j6ETuoneLDyQKQUGZFaNCrzdl4mG1PLK/xqPAzVtMX64B1AH2i29Xg3y4SWEjZRyUhA45gjhr30b0iJLDS3sqRO02i6/Tfl/Ao44gNvQ39tF70Ur5Iy6Dp8Bw=
