dist: trusty
addons:
  chrome: stable
language: node_js
before_install:
- export CHROME_BIN=google-chrome-stable
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem install mdl
cache:
  directories:
  - node_modules
script: npm run ci
env:
  global:
    secure: IwrgbctVFzA4drrQ4KygvnL0F/HGEEAO5rfR+tuIG2wX8SJe5N0rMBcgtiVJGXjjm0HEx+LjLVVTx9kpwAFmn2CVcJwWFN87R8OS+PqbMhrSGN9vopcmr4Oruo8adbHtmwpeGEdGVpv2XYseqdmELTQU1KFUBAoRphZacG02YC3YK3taNII6qcrChGTmBszLiLRNFIQzirG+/JxPZi16Axq7Iz9KUXhtcIil330lmhsSWtZQBQZD45MBdqd2Amj1SWnLTMKtoEnqJ1z+EdFKjFBN5gdJOyes2sGe6QiGRQjC3JTA2JuUiS4nNthRXwRKy9aYVdjTv4sae5JM00LX0Ytmo52Ie/83/Gj6CwH8E8pJT9fk7WnKDlr0LjbXiLNRh+jJ7reIhFdOcaD7XBLjOkrGKetjT5QrsthdpEZ3ydPzi0Rro/mR3Syqp/sll+GA6hRCFXL5+QiLWX22XVmanN6O4kfMMv8/6gV+apZhCer3xGTOO2hlXuSt+BGpf20EMCPI26Tw0etmN5zDI8vRM6YVlRYq0IilxjflcS3o8X89QHcWny4HJFcZvKCrKONfftoqwR+pRhgkcyA8o0CGZ9TG5NsEQp9EMoY4j5WIT0TGWaXIOjkJIf07FCCTlE91XsRwILxbSuVAOIHsWeUtJgI41n4QqN1d4/NghjjsPik=
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter > coverage/lcov.info
before_deploy: npm run build --prod --progress false
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: firebase
  token:
    secure: C/ijVEECipluzfapXKOnXp1dy0y65knHmVQ5oMINK6gzTxFKGxjPKvmQVkK8o50VL+zsqDcsYq/dySI357Ls8vDekLoWJqb7ZkcDGS+4vxcj4L9zjKAv6dOeLF8Ng3bXIkCJ1sNSTrzBMKS2CxHlceWiDjM6XaybGuvWLufCXvUQh7rUCeleTdvTFLBnN3zB+fpIVhruOfgoU74nhBolv9/9PWsr0P8JZA1RyN0CqYkUGbS7TkEsnKM+ih3f+e3RhF7MtCyuAoD+UegUfNhoX6GrOxMkM0eP98mnWB9p8qoTUcd+z9G44x97oNtzG9+cqhTb4B42jGcVumMdSDVZqysBvEotJMf4G+PASycdsyF+OuIr2m7yLt/dzlUn5Lv+MOOjf34BDT98KbXKyeuM9zgKtvEI/1h1VJTccZr/Is8igTtoR05+xhQ1o/W0EsMDRzCWFiApysST07am8quv3yLr8MK8dOVl0OpGGJL7oo/bw1Q3ru/bFx1iq2O/iKIr1lEiqdXs4Ubbk7l8i0eYeDP1I6vFvAeKi1j7/A1R9UQcroUBPNppHagQBfy7VfaRt20FZO8NahucoK3ZLL/1RjXwxF4pwznMXO5/quTXEcSXauxXoK7XKptgmeZ+BkfCjH7ysn6eK/SGXBHmMd6y4NLfpy7g4O9D5spqluwzDb0=
  project: sanhei-bills
