dist: trusty
addons:
  chrome: stable
language: node_js
before_install:
- export CHROME_BIN=google-chrome-stable
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- bin/setup
node_js:
- node
cache:
  directories:
  - node_modules
script: npm run ci
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: firebase
  token:
    secure: O3m5btCEl+pWte9qFEbfm5n3YTsrM+FwIhlx4xjNgO+MHKoyTJMujwvzFywNkzJK+DrqiEAqA3JWCGbW0ftEc4K+RT+BY1xLOlbUlKnoYQPFbVfdt/HFuKNsMAFthWvzeDwYTcbUYKvxL+V10VvjpFva8iVOB+TbNXs5MtYJ1lnV4a7oSFpGqb0O/KATaV9Z1pvCcNGcez9WOm9hTno2qLgjkjoZOAPIf90ZmKb6iylgiumX0cFoE5WUu7yFbZLE4c5QWJ/i5J6/gtm7A0l7pQQwJcnd78/m9fDHmmSgfDAgL9uRWUZDaZpqkNlaXhMtt9YSkspCncaX97m9OzhYasQxJ1FS12ayUMVj7yw8t/vdYwFUaVwSLWAFZ+DZAd+zEAVrG6vReAyHXLyovDaEA2IXbk/U6ChmdQP9NeAXcZbxsuHSehcT4bRC2/OHbVadYb/YSBrSxVrZ5ta+uHlr8J4hSVOJ+5QCZSPl2qezSgbSd7aUx36HyJiBCUQzYeeDnRCp2qJ8XNQOirPd+hNRcTcCq3LvOU1QpOT20RcwljdaWQVrPEFS3Js9R5+M9JqpMlyoxTob0Y6OEMdmWqdXLiCvhjH+4YXLXpGe+0WTuN++EZtYyb+eU2oicQniAjXI1GlaNt9y2SEfmQ1gW1spf10nk4Gx6jYerf/yB48ZKkw=
