dist: trusty
addons:
  chrome: stable
language: node_js
before_install:
  - export CHROME_BIN=google-chrome-stable
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bin/setup
node_js:
  - "node"
cache:
  directories:
  - node_modules
script: npm run ci
