name: Deploy main
on:
  push:
    branches: [main]
jobs:
  deploy-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - run: yarn install
      - run: cd functions && yarn install && cd ..

      - run: cd functions && yarn run ci && cd ..
      - run: yarn run ci

      - run: yarn run deploy-main
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
