name: Deploy main
on:
  push:
    branches: [main]
jobs:
  deploy-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - run: yarn install
      - run: cd functions && yarn install && cd ..

      - run: cd functions && yarn run ci-before-build && cd ..
      - run: yarn run ci-before-build
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SANHEI_BILLS }}'
      - run: yarn run deploy-main
        # env:
        # see https://github.com/FirebaseExtended/action-hosting-deploy/blob/main/docs/service-account.md
        # see https://github.com/google-github-actions/auth?tab=readme-ov-file
        # the key is stored here: https://console.cloud.google.com/iam-admin/serviceaccounts?project=sanhei-bills&supportedpurview=project
        # the service account token is stored here: FIREBASE_SERVICE_ACCOUNT_SANHEI_BILLS
        # this was the old way: FIREBASE_TOKEN:  secrets.FIREBASE_SERVICE_ACCOUNT_SANHEI_BILLS }}
