name: Deploy main
on:
  push:
    branches: [main]
jobs:
  deploy-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - run: yarn install
      - run: cd functions && yarn install && cd ..

      - run: cd functions && yarn run ci-before-build && cd ..
      - run: yarn run ci-before-build

      - run: yarn run deploy-main
        env:
          # run firebase login:ci to get a new token
          # store it in https://github.com/lukaselmer/sanhei-bills2/settings/secrets/actions
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
