name: Test & Lint
on: 'push'
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - run: cd functions && yarn install && cd ..
      - run: yarn install

      - run: cd functions && yarn run ci && cd ..
      - run: yarn run ci
